name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup database
        run: bin/rails db:create db:migrate
        env:
          RAILS_ENV: test

      - name: Build Tailwind CSS
        run: bin/rails tailwindcss:build
        env:
          RAILS_ENV: test

      - name: Run tests
        run: bundle exec rspec --exclude-pattern "spec/system/**/*"
        env:
          RAILS_ENV: test
